name: weather
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  intl: ^0.17.0
  http: ^0.13.1
  dio: ^4.0.0
  google_maps_flutter: ^2.0.1
  json_serializable: ^4.1.0
  build_runner: ^1.12.2
  json_annotation: ^4.0.0
  shared_preferences: ^2.0.5
  geolocator: ^7.0.1
  provider: ^5.0.0
  theme_provider: ^0.5.0
  url_launcher: ^6.0.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.1.1
  very_good_analysis: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
